[profile.ci.fuzz]
runs = 10_000

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@chainlink-local/=lib/chainlink-local/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC}"
polygon = "${POLYGON_RPC}"
arbitrum = "${ARBITRUM_RPC}"
avalanche = "${AVALANCHE_RPC}"
optimism = "${OPTIMISM_RPC}"
base = "${BASE_RPC}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
